language: python

services:
  - docker

before_install:
  - docker pull dinutac/jinja2docker:latest
  - docker-compose up -d
  - sleep 10
  - docker exec jinja2docker python3 -m unittest discover ${SCRIPTS_DIR} "*_test.py"
  - docker-compose down -v