language: python

services:
  - docker

deploy:
  - docker build -t dinutac/jinja2docker:latest .
  - docker-compose up -d
  - sleep 10

install:
  - docker exec jinja2docker python3 -m unittest discover ${SCRIPTS_DIR} "*_test.py"

after_deploy:
  - docker-compose down -v