kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: jinja2docker
  name: jinja2docker-service
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    k8s-app: jinja2docker
